version: '3'

services:
  nginx:
    container_name: son-be-nginx
    build:
      context: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html:delegated
    depends_on:
      - mysql
  php:
    container_name: son-be-php
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    user: bimantara
    volumes:
      - ./:/usr/share/nginx/html:delegated
    working_dir: /usr/share/nginx/html
    depends_on:
      - mysql
  mysql:
    container_name: son-be-mysql
    build:
      context: ./docker/mysql
    ports:
      - 3306:3306
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: b1sm1ll4h
      MYSQL_DATABASE: son-be
  # redis:
  #   container_name: son-be-redis
  #   build:
  #     context: ./docker/redis
  #   ports:
  #     - 6379:6379
  # jenkins:
  #   build:
  #     context: ./docker/jenkins
  #   container_name: son-be-jenkins
  #   privileged: true
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8080:8080
  #     - 50000:50000
